### ISSUE TITLE
Requesting for a material theme layout since most are using Android post 13.

### ISSUE THREAD

**Issue by Varniit-pro-90s** [FossifyOrg/Music-Player#10]
Requesting for a material theme layout since most are using Android post 13.

This is for all apps.

Also, I'm requesting for music player layout like Spotify player screen and buttons at bottom due to big phones.

Equalizer inbuilt for pitch and tempo and audio speed.

Podcasts player and video player would also be recommended.

![Screenshot_2024-01-14-21-26-28-500_org schabi newpipe](https://github.com/FossifyOrg/Music-Player/assets/156216269/78ebeddb-6681-4820-8a48-052c46b01023)

**Checklist**
 - [ ] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [ ]  I have read the FAQ and my problem isn't listed.
 - [ ]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [ ]  This issue contains only one feature request.
 - [ ]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aga-C** [comment]
> Requesting for a material theme layout since most are using Android post 13.
> This is for all apps.

There is already a Material theme in every app.

Also, please fill out the template properly.

BTW. Are you sure you are filling the issue for the proper app? Because on the screenshot there isn't Simple Music Player.

**Comment by Varniit-pro-90s** [comment]
> > Requesting for a material theme layout since most are using Android post 13.
> > This is for all apps.
> 
> There is already a Material theme in every app.
> 
> Also, please fill out the template properly.
> 
> BTW. Are you sure you are filling the issue for the proper app? Because on the screenshot there isn't Simple Music Player.

This is for reference for "Equalizer inbuilt for pitch and tempo and audio speed."

**Comment by Aga-C** [comment]
Please clarify your request by filling out the template properly and raise just one request in one issue.

**Comment by Varniit-pro-90s** [comment]
> Please clarify your request by filling out the template properly and raise just one request in one issue.

Please delete the post (i dont know how to delete it). I have mailed instead. I am new at GH so also dont know the procedure.
