### ISSUE TITLE
Accrescent app store

### ISSUE THREAD

**Issue by ellie3-36** [FossifyOrg/Music-Player#109]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Accrescent is an Android app store focused on security, privacy, and usability. Would love to see Music Player app available in Accrescent.

Some relevant links:

Official website: https://accrescent.app/

Docs: https://accrescent.app/docs/index.html

Contact: [contact@accrescent.app](mailto:contact@accrescent.app) 

### Why do you want this feature?

Because of Accrescent features:
https://accrescent.app/features

**Comment by Aga-C** [comment]
See: https://github.com/orgs/FossifyOrg/discussions/228.
