### ISSUE TITLE
Support tagging.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [FossifyOrg/Music-Player#28]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

A one-to-many correspondence, possible to combine and exclude when filtering.

### Why do you want this feature?

To organize them in a manner which embeds into the audio/music file, or via the file system as https://github.com/FossifyOrg/File-Manager/issues/60#issue-2151476679 requests, but via the Notes GUI for the sake of accessibility to the technically less competent, and convenience for all, regardless of competence.

### Additional information

https://github.com/FossifyOrg/General-Discussion/issues/127#issuecomment-1958772679

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FossifyOrg/Music-Player/issues/28#issuecomment-1961712164

I didn't notice it. Perhaps I just forgot. Thanks for the correction, @Aga-C.

**Comment by marcosox** [comment]
> App currently has ID3 tags support

Just to confirm, there is no ID3 tag edit functionality at the moment, right?

**Comment by Aga-C** [comment]
@marcosox We support editing title, artist and album in MP3 files.

**Comment by marcosox** [comment]
> [@marcosox](https://github.com/marcosox) We support editing title, artist and album in MP3 files.

How? I can't find any way to do that (I tried tapping and long tapping on every UI item I could think of) nor any documentation (the site says "under construction", the music player is not listed among the apps in the site, there is nothing under "wiki" or "discussions" in this github repo and there is no `doc` folder in the source code). If it's possible I think it's not very discoverable for users.

**Comment by naveensingh** [comment]
Long-press any file ➜ Rename

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/f4f8a3c3-cea6-4300-8d11-771869090367" width=178 />

**Comment by beedell-roke** [comment]
@naveensingh, long-press is a fairly unintuitive design decision. Can it not be accessed via any alternative GUI element? I know of a few organisations (like KDE) which explicitly disallow long-press for the sake of accessibility. (Google doing so isn't a good example.)

**Comment by naveensingh** [comment]
I guess it's subjective. On Android and other touch-screen focused operating systems, long-press is like a standard and intuitive _once_ you get used to it. I agree that it would be a nightmare in other environments, like desktops.

We could do an overflow button on every list item, but it would look cluttered. Fossify apps are more Gnome than KDE ;)

**Comment by marcosox** [comment]
It wouldn't occur to me in a lifetime to use the "rename" option to edit the ID3 tags of an mp3 file. Indeed the "rename" dialog allows the user to both rename the actual file (with separate textboxes for the name and the extension?? 🤔 ) **and** edit the ID3 tags. First place where I looked for this is in the "currently playing" view, long-tapping over the song title/author.

I find this _very_ confusing. Now that you made me stop and think about it... why is the music player even involved in the renaming of files? Isn't that the file manager's job?

I appreciate the spirit of adding "useful" features, but I believe this ended up overcomplicating the UI and confusing the users. My humble opinion of course.

**Comment by beedell-roke** [comment]
@naveensingh, ha. A similar discussion at exists at [`gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2662#note_1686023`][1], though, of which some corroborates what I've stated:

> I agree with the need for a fast way to get to the relevant Settings page, but using long-click seems both undiscoverable and inconsistent with platform standards.
> 
> How about going with a more tried-and-true method of displaying a context menu containing a "Settings..." item on both right-click and long-tap?

[1]: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2662#note_1686023:~:text=I%20agree%20with%20the%20need,on%20both%20right%2Dclick%20and%20long%2Dtap?

It's a minority opinion *there*, but that shouldn't discount it alone.

**Comment by naveensingh** [comment]
> It wouldn't occur to me in a lifetime to use the "rename" option to edit the ID3 tags of an mp3 file

Well, it's an old design. Things weren't always done with UX in mind. Functionality was the main focus (rightly so).

> I appreciate the spirit of adding "useful" features, but I believe this ended up overcomplicating the UI and confusing the users. 

It will be simplified.

**Comment by beedell-roke** [comment]
> why is the music player even involved in the renaming of files? Isn't that the file manager's job?

@marcosox, I agree with you on that point. The file manager can modify XDG Extended Attributes, because these are stored within the filesystem. However, all else are generally within the purview of either an integration to the file manager, or the relevant application itself (in this case, Fossify's Music Player), since the relevant attributes're stored within the file.

**Comment by marcosox** [comment]
I just tried to edit ID3 tags for a song and when I tapped OK it said "unknown error". If anybody can tell me how to collect logs and/or other needed info I can open another issue

**Comment by naveensingh** [comment]
I can reproduce it too. Please consider filing one.

**Comment by naveensingh** [comment]
It doesn't happen in debug builds. Interesting.

Update: It's an obfuscation issue. Fix ready. Waiting for bug report :)

**Comment by marcosox** [comment]
> It doesn't happen in debug builds. Interesting.
> 
> Update: It's an obfuscation issue. Fix ready. Waiting for bug report :)

#206
