### ISSUE TITLE
 Add support for the .m4a file format.

### ISSUE THREAD

**Issue by lriaudel** [FossifyOrg/Music-Player#37]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I have an error when I lauch a m4a file. I think this format is not used by this app.

### Why do you want this feature?

I want to use fossify music player to listen a m4a format downloaded from newpipes https://newpipe.net/.
But I have an error when i lauch that. I think this format is not used by this app.

### Additional information

Thanks for your work.

**Comment by Aga-C** [comment]
The M4A format is supported by the app. I even was able to play audio downloaded by NewPipe. Maybe try restarting the app or try to download the audio track once again.

**Comment by Gamer750** [comment]
It is not working in my phone

**Comment by chesio** [comment]
> It is not working in my phone

It must be a device specific issue, so it would help if you provide more info (device model, Android version, Music Player app version...)
