### ISSUE TITLE
Skip Uses Wrong Button Icon

### ISSUE THREAD

**Issue by bigboipete** [FossifyOrg/Music-Player#53]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Music-Player/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

ShiftOS 2.0 L (basically AOSP 8.1)

### Affected device model

Shift5me

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

This is a rather formal issue (I wouldn't call it a bug): 
1. Open App
2. Start playing a song
3. See [this](https://github.com/FossifyOrg/Music-Player/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png) screen

### Expected behavior

The skip next/back functionality should use the [common skip buttons](https://cdn4.iconfinder.com/data/icons/media-controls-4/100/skip-ahead-512.png).

### Actual behavior

The skip functionality is displayed by the common fast-forward/fast-backward buttons.

### Additional information

[Wikipedia: Media Control Symbols](https://en.wikipedia.org/wiki/Media_control_symbols)

**Comment by LOUTFI94** [comment]
Hello,
@Bmarwane93 and i we are students at the Paris 8 University (France) and we'd love to be assigned to this task as part of our "free software development" course.
it possible ?
Thank you in advance

**Comment by naveensingh** [comment]
@LOUTFI94 you are welcome to raise a PR. Please use the material design rounded buttons, click [here](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:skip_next:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=skip&icon.style=Rounded) for an example.

The drawables should be named `ic_next_vector.xml` and `ic_previous_vector.xml` and formatted using https://github.com/alexjlockwood/avocado for consistency.

**Comment by Bmarwane93** [comment]
Hello here are the changes made, we are beginners in android development, we are doing some research to use avocdo

 
format icon with avocado:
<img width="791" alt="avocado_icon_xml" src="https://github.com/FossifyOrg/Music-Player/assets/95193272/763f3ee9-61fc-457a-8592-97ac6ae31672">


BEFORE : 
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
  <path
      android:pathData="M220,720v-480h80v480h-80ZM740,720L380,480l360,-240v480Z"
      android:fillColor="#5f6368"/>
</vector>
```
       
AFTER : 
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="960" android:viewportHeight="960">
<path android:fillColor="#FF000000" android:pathData="M220 720V240h80v480h-80zm520 0L380 480l360-240v480z"/>
</vector> 
```

a screen shot of the result :
![Screenshot_skip_button_icon](https://github.com/FossifyOrg/Music-Player/assets/95193272/0bab865d-0c67-46c6-a46b-256b9a1a9090)

**Comment by Bmarwane93** [comment]
https://github.com/FossifyOrg/Music-Player/pull/55

**Comment by naveensingh** [comment]
Fixed by https://github.com/FossifyOrg/Music-Player/pull/55
