### ISSUE TITLE
Shuffle All

### ISSUE THREAD

**Issue by bigboipete** [FossifyOrg/Music-Player#71]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It might be possible, that this feature already exists and I didn't manage to find it. If so, I'd really like to know how to access it in Fossify Music-Player.

I'd like to see a "Shuffle all" button/menu entry, that shuffles the whole library and starts playing all available songs in random order. The AOSP player does have this, as far as I know.

### Why do you want this feature?

The benfit of that approch is - at least for me - that you don't need to mess around with playlists and just listen to all the music files on your device.

There are certainly other ways to organise and keep audio files on a device, but I very deliberatly load music (only) on it. I want to hear all songs, that are there - no podcasts, audio-books, etc. - and change the collection on a regular basis.

**Comment by bigboipete** [comment]
@Aga-C Could you please be a bit more verbose, where to find it in Fossify Music-Player and provide some steps how to access and manage it? I have no entries in the playlist tab.

Thanks in advance.

**Comment by Aga-C** [comment]
By default, there's such a playlist in the playlists tab. Maybe you've deleted it. You can reinstall the app to get it back.

**Comment by bigboipete** [comment]
Wow... to ease this, it could be another feature request right away. But thanks for the reply.
