### ISSUE TITLE
Visibility and order of 'Now Playing' screen elements

### ISSUE THREAD

**Issue by user24024** [FossifyOrg/Music-Player#78]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add additional customization options for the 'Now Playing' screen.

### Why do you want this feature?

To have better usability.

### Additional information

I would like to have the option to choose the visibility and order of elements on the 'Now Playing' screen.
For example, I'd like the seekbar to be at the very bottom, where it's easier to reach.

I would also like an option to have the playback speed control slider always visible (and, if implemented in #76  and #77 , playback pitch control and playback balance control sliders as well). The space needed for the slider(s) could be made available either by making the album cover field smaller, or by having the option to disable it altogether (as suggested in #8 ). This might be a separate feature, but it's all very intertwined, so I'm not sure if it should be in a separate request.

If implementing a way for the user to change the order of elements would be too much, my personal suggestion (although this is very subjective) would be to have the elements in the following order (top to bottom):

-Album cover
-Track info
-(if implemented) Playback balance slider
-(if implemented) Playback pitch slider
-(if implemented) Playback speed slider
-Playback buttons
-Seekbar

...where the elements used the most are at the bottom, so they're easier to reach with the thumb, and elements used the least are at the top.

**Comment by Aga-C** [comment]
There is already a request for that, please add your remarks to it: https://github.com/FossifyOrg/Music-Player/issues/31.

**Comment by user24024** [comment]
Thanks, apologies for the duplicate.
