### ISSUE TITLE
Output to DLNA renderer

### ISSUE THREAD

**Issue by Kazcade** [FossifyOrg/Music-Player#80]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I don't know if this is even within the scope of the project, but would it be possible to add an option to output audio to DLNA renderers (TV, A/V receivers etc) instead of locally? I am currently looking for a lightweight FOSS player with a working music library that enables me to stream audio to my receiver, but as far as I can tell nothing of that sort exists.

Plain UPnP, ControlDLNA, YAACC and DroidUPnP are all lacking in that regard aas none of these are actual music players and lack the functionality of Music-Player (including an actual working library view).

The only "alternatives" (bubbleupnp, neutron player, hifi cast...) are closed source and either laden with ads or paid (or both) and try to do more than output audio.

### Why do you want this feature?

To stream high quality audio from my Android device to my home audio system.

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this.
