### ISSUE TITLE
Enabling shuffle does not change icon color when using "System Default (Material You)" theme

### ISSUE THREAD

**Issue by Luiz-C-Lima** [FossifyOrg/Music-Player#82]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Music-Player/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Realme C67

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the app
2. Use "System Default (Material You)" theme
3. Enable or disable shuffle

### Expected behavior

The shuffle icon to change color like when using other themes.

### Actual behavior

The shuffle icon does not change the color.

### Screenshots/Screen recordings

![disabled](https://github.com/user-attachments/assets/c83b9649-99e1-423d-8af9-15d04e3fe1d8)
![enabled](https://github.com/user-attachments/assets/545623e9-ea6c-43e6-b5f4-c6d16595ad25)

**Comment by Aga-C** [comment]
This should be the same color as the search bar or tabs at the bottom. Can you show how these parts of the app look on your device?

**Comment by Luiz-C-Lima** [comment]
![color](https://github.com/user-attachments/assets/fa0935e1-58c3-45ad-86df-5b35817af477)

**Comment by Aga-C** [comment]
So, it took the good color. We apply a bit of transparency to the text color to show the inactive button, and it happened to be the same color as your primary color (which we use for the activated button). This combination is really very unlikely to happen.

**Comment by chesio** [comment]
I do have the same problem, so it might not be as unlikely as it seems... :-)

**Comment by naveensingh** [comment]
This is essentially a duplicate of https://github.com/FossifyOrg/Music-Player/issues/60. I proposed a solution here: https://github.com/FossifyOrg/Music-Player/issues/60#issuecomment-2085709569
