### ISSUE TITLE
Scrobbling Support

### ISSUE THREAD

**Issue by RuralAnemone** [FossifyOrg/Music-Player#84]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Last.fm (, libre.fm, etc) scribbling support.

### Why do you want this feature?

I love this app and its simplicity but the only drawback for me is the lack of scrobbling integration.

**Comment by RuralAnemone** [comment]
I could also work on this myself and pr but it might be a while as I haven't ever used the last.fm API (nor developed for mobile)

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this.
