### ISSUE TITLE
korean text (track titles) displayed as ????????

### ISSUE THREAD

**Issue by Mangoes** [FossifyOrg/Music-Player#87]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Music-Player/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Pixel 8 pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. play a track with korean text in the title

### Expected behavior

The track title should be displayed with the Korean font.

### Actual behavior

The track title is displayed as ???????

It looks like the proper font is missing (but in the android file manager it is displayed correctly, so the system has the font).

My guess is that the same probably also happens with other languages like Japanese, Chinese, Thai, etc... These should be tested as well.

**Comment by Aga-C** [comment]
Please attach a file that displays wrong title and also attach the screenshot. I can't reproduce it.

**Comment by Mangoes** [comment]
Here is the [file link](https://mega.nz/file/ccVjxRpK#UT5QyKxqtfQNfAGuR34OtoMtO5Vrs_WEK4Hnh4EmP44)

Screenshot:
![IMG_20240903_213603](https://github.com/user-attachments/assets/3be56946-93c1-421b-8576-5e2b8e028b3d)

**Comment by Aga-C** [comment]
Actually, this file has `?? ???` set as a title in its metadata, it's not a bug in the app. In a file manager, you can see the Korean characters in the file title, but when you check the metadata of the file in any app, you will see `?? ???` as the track title. I've checked this file on a mobile and PC with VLC, foobar2000, MPV, metaflac, and all of these apps were showing `?? ???`.

Here's what metaflac (official FLAC tool for tagging FLAC files) returns after inspecting this file:

```
ARTIST=Yiruma
TITLE=?? ???
ALBUM=Yiruma & Piano CD3
Date=2011
GENRE=New Age
Description=L2Bits, EAC V1.0 beta 3 Secure Mode, Test & Copy, AccurateRip, FLAC -8
ALBUMARTIST=Yiruma
TRACKNUMBER=01
TOTALTRACKS=13
```

**Comment by Mangoes** [comment]
Yes you are right.

Sorry about that.
