### ISSUE TITLE
Feature Suggestion: Integrate Audius Music's Free API

### ISSUE THREAD

**Issue by T3kn3vra** [FossifyOrg/Music-Player#92]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Overview:
I would like to propose that Fossify Music Player consider potemtially integrating the Audius Music Free API to expand its music streaming capabilities and offer users access to a vast library of independent artist content.

What is Audius?

Audius is a decentralized music streaming platform that allows artists to upload and share their music directly with listeners. It offers a free API that enables developers to integrate Audius content into their applications.

### Why do you want this feature?

Benefits of Integration
- Expanded Music Library: Provide users access to millions of tracks from independent artists.

- Support for Indie Music: Align with Fossify's open-source ethos by supporting a decentralized music platform.

- No Licensing Fees: Audius content is free to stream, potentially reducing costs for Fossify.

- User Engagement: Attract users interested in discovering new, independent music.

__________________________________________

Proposed Features:

- Audius Search: Allow users to search and play Audius tracks within Fossify Music Player.

- Playlist Integration: Enable users to create and save playlists that include both local and Audius tracks.

- Artist Discovery: Implement features to help users discover new Audius artists based on their listening habits.

- Offline Caching: Provide an option to cache Audius tracks for offline playback.

____________________________________________
Technical Considerations:

- API Implementation: Utilize the Audius API to fetch track metadata, streaming URLs, and artist information.

- User Authentication: Implement Audius user authentication to access personalized features.

- Caching Mechanism: Develop a system to efficiently cache and manage Audius content locally.

- UI/UX Updates: Design intuitive interfaces to seamlessly integrate Audius content with local music libraries.

___________________________________________
Potential Challenges:

- Content Moderation: Develop strategies to handle potentially inappropriate content from the Audius platform.

- Network Performance: Ensure smooth playback of streaming content, especially on slower connections.

- API Limitations: Be aware of and work within any rate limits or restrictions of the Audius API.

_____________________________________________

Conclusion:

Integrating the Audius Music Free API into Fossify Music Player could SIGNIFICANTLY enhance the app's functionality and appeal to a broader user base.

 It aligns well with Fossify's open-source philosophy and could position the player as a unique offering in the music app landscape.

I personally believe that this integration could be a valuable addition to Fossify Music Player and would be excited to see it implemented in future versions.

_____________________________________________

### Additional information

LINKS:

AUDIUS MUSIC WIKIPEDIA:
https://de.wikipedia.org/wiki/Audius

AUDIUS GITHUB:
https://github.com/AudiusProject
https://audiusproject.github.io/api-docs/#audius-api-docs

AUDIUS MUSIC WEBSITE:
https://audius.co/

https://audius.org/

AUDIUS MUSIC API:
https://audius.org/en/api

Docs: https://docs.audius.org

https://docs.audius.org/api/

https://docs.audius.org/developers/guides/log-in-with-audius/

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this.
